server:
  host: "app host"
  port: 8080

app:
  name: "app name"
  environment: development
  debug: true
  log_level: debug

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "db_name"
  sslmode: "disable"

JWT:
  secret: "secretKey"
  expire: 3600